export const skills = {
  languages: [
    {
      id: 1,
      title: 'C',
      src: '/icons/c-lang.svg',
      link: 'https://www.c-language.org/',
    },
    {
      id: 2,
      title: 'JavaScript',
      src: '/images/javascript.png',
      link: 'https://javascript.info/',
    },
    {
      id: 3,
      title: 'TypeScript',
      src: '/icons/typescript.svg',
      link: 'https://www.typescriptlang.org/',
    },
  ],
  frontend: [
    {
      id: 4,
      title: 'HTML',
      src: '/icons/html.svg',
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
    },
    {
      id: 5,
      title: 'CSS',
      src: '/icons/css.svg',
      link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    },
    {
      id: 6,
      title: 'Bootstrap',
      src: '/icons/bootstrap.svg',
      link: 'https://getbootstrap.com/',
    },
    {
      id: 7,
      title: 'Tailwind CSS',
      src: '/icons/tailwind-css.svg',
      link: 'https://tailwindcss.com/',
    },
    {
      id: 8,
      title: 'React.js',
      src: '/icons/react.svg',
      link: 'https://react.dev/',
    },
    {
      id: 9,
      title: 'Shadcn UI',
      src: '/images/shadcn-ui.png',
      link: 'https://ui.shadcn.com/',
    },
    {
      id: 10,
      title: 'Material UI',
      src: '/icons/material-ui.svg',
      link: 'https://mui.com/material-ui/',
    },
    {
      id: 11,
      title: 'Chakra UI',
      src: '/icons/chakra-ui.svg',
      link: 'https://chakra-ui.com/',
    },
  ],
  backend: [
    {
      id: 12,
      title: 'Node.js',
      src: '/icons/node-js.svg',
      link: 'https://nodejs.org/en',
    },
    {
      id: 13,
      title: 'Express.js',
      src: '/icons/express-js.svg',
      link: 'https://expressjs.com/',
    },
    {
      id: 14,
      title: 'Hono.js',
      src: '/icons/hono-js.svg',
      link: 'https://hono.dev/',
    },
    {
      id: 15,
      title: 'Fastify.js',
      src: '/icons/fastify-js.svg',
      link: 'https://fastify.dev/',
    },
  ],
  database: [
    {
      id: 16,
      title: 'MongoDB',
      src: '/icons/mongo-db.svg',
      link: 'https://www.mongodb.com/',
    },
    {
      id: 17,
      title: 'Mongoose',
      src: '/icons/mongoose-js.svg',
      link: 'https://mongoosejs.com/',
    },
    {
      id: 18,
      title: 'PostgreSQL',
      src: '/icons/postgresql.svg',
      link: 'https://www.postgresql.org/',
    },
    {
      id: 19,
      title: 'Prisma',
      src: '/icons/prisma.svg',
      link: 'https://www.prisma.io/',
    },
    {
      id: 20,
      title: 'Firebase',
      src: '/icons/firebase.svg',
      link: 'https://firebase.google.com/',
    },
  ],
  advanced: [
    {
      id: 21,
      title: 'Next.js',
      src: '/icons/next-js.svg',
      link: 'https://nextjs.org/',
    },
    {
      id: 22,
      title: 'TanstackQuery',
      src: '/images/tanstack.png',
      link: 'https://tanstack.com/query/latest',
    },
    {
      id: 23,
      title: 'Redis',
      src: '/icons/redis.svg',
      link: 'https://redis.io/',
    },
    {
      id: 24,
      title: 'Motion',
      src: '/images/motion.png',
      link: 'https://motion.dev/',
    },
    {
      id: 25,
      title: 'GSAP',
      src: '/icons/gsap.svg',
      link: 'https://gsap.com/',
    },
  ],
  tools: [
    {
      id: 26,
      title: 'Git',
      src: '/icons/git.svg',
      link: 'https://git-scm.com/',
    },
    {
      id: 27,
      title: 'GitHub',
      src: '/icons/github.svg',
      link: 'https://github.com/',
    },
    {
      id: 28,
      title: 'Docker',
      src: '/icons/docker.svg',
      link: 'https://www.docker.com/',
    },
    {
      id: 29,
      title: 'Kafka',
      src: '/icons/apachekafka.svg',
      link: 'https://kafka.apache.org/',
    },
    {
      id: 30,
      title: 'Kubernetes',
      src: '/icons/kubernetes.svg',
      link: 'https://kubernetes.io/',
    },
    {
      id: 31,
      title: 'Jest.js',
      src: '/icons/jest-js.svg',
      link: 'https://jestjs.io/',
    },
    {
      id: 32,
      title: 'Vitest',
      src: '/icons/vitest.svg',
      link: 'https://vitest.dev/',
    },
  ],
}
