FROM node:22.21.1-alpine3.21

WORKDIR /app

# Install pnpm
RUN corepack enable pnpm
RUN corepack prepare pnpm@latest --activate

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["pnpm", "dev", "--turbopack"]
